name: CreateTag

on:
  push:
    branches:
      - production

jobs:
  auto-versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Determine next version
        uses: SOLIDSoftworks/semver-tags@v1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          tag-prefix: 'v'
          default-version: '0.0.1'
          prerelease: 'alpha'
          create-release: branch_name
